markdown: redcarpet
highlighter: pygments

title_tag_text: John Brewster Architect
h1_tag_text: John Brewster Architect

include: ['_pages']

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]

encoding: UTF-8

url: https://johnbrewster.net   # with the https protocol
enforce_ssl: johnbrewster.net   # without any protocol
