markdown: redcarpet
highlighter: pygments

title_tag_text: John Brewster Architect
h1_tag_text: John Brewster Architect

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
